#!/usr/bin/env python3
"""Generate the small offline lunar/solar-term table used by the device.

The generator uses lunar-python 1.4.8 (MIT), but the firmware only contains
the generated C data and has no Python or network dependency at runtime.
Install the pinned tool into a temporary environment, then run:

    PYTHONPATH=/tmp/lunar_python_148 python3 tools/generate_lunar_table.py

Source: https://github.com/6tail/lunar-python (MIT License)
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

from lunar_python import Lunar, LunarYear, Solar

START = dt.date(1900, 1, 1)
END = dt.date(2100, 12, 31)
TERMS = tuple(Lunar.JIE_QI)


def solar_date(julian_day: int) -> dt.date:
    value = Solar.fromJulianDay(julian_day)
    return dt.date(value.getYear(), value.getMonth(), value.getDay())


def ordinal(value: dt.date) -> int:
    return (value - START).days


def make_months() -> list[tuple[int, int, int, int, int]]:
    rows: list[tuple[int, int, int, int, int]] = []
    for lunar_year in range(1899, 2102):
        for month in LunarYear.fromYear(lunar_year).getMonths():
            if month.getYear() != lunar_year:
                continue
            date = solar_date(month.getFirstJulianDay())
            if START <= date <= END:
                rows.append(
                    (ordinal(date), lunar_year, month.getMonth(), month.getDayCount(), 0)
                )
    rows.sort(key=lambda row: row[0])
    return rows


def make_terms() -> list[tuple[int, int, int, int]]:
    rows: list[tuple[int, int, int, int]] = []
    seen: set[tuple[int, int]] = set()
    for lunar_year in range(1899, 2102):
        table = Lunar.fromYmd(lunar_year, 1, 1).getJieQiTable()
        for index, name in enumerate(TERMS):
            value = table.get(name)
            if value is None:
                continue
            date = dt.date(value.getYear(), value.getMonth(), value.getDay())
            key = (ordinal(date), index)
            if START <= date <= END and key not in seen:
                rows.append((key[0], index, 0, 0))
                seen.add(key)
    rows.sort(key=lambda row: row[0])
    return rows


def emit(months: list[tuple[int, int, int, int, int]], terms: list[tuple[int, int, int, int]]) -> None:
    root = Path(__file__).resolve().parents[1]
    header = root / "main" / "lunar_table.h"
    source = root / "main" / "lunar_table.c"
    header.write_text(
        """#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\ntypedef struct {\n    uint32_t solar_day;\n    int16_t lunar_year;\n    int8_t lunar_month;\n    uint8_t lunar_days;\n} lunar_month_record_t;\n\ntypedef struct {\n    uint32_t solar_day;\n    uint8_t term_index;\n} lunar_term_record_t;\n\nextern const lunar_month_record_t lunar_month_table[];\nextern const size_t lunar_month_table_count;\nextern const lunar_term_record_t lunar_term_table[];\nextern const size_t lunar_term_table_count;\n""",
        encoding="utf-8",
    )
    with source.open("w", encoding="utf-8") as stream:
        stream.write(
            """/* Generated by tools/generate_lunar_table.py.
 * Data source: lunar-python 1.4.8, MIT License.
 * Range: Gregorian 1900-01-01 through 2100-12-31.
 */
#include "lunar_table.h"

"""
        )
        stream.write("const lunar_month_record_t lunar_month_table[] = {\n")
        for day, year, month, days, _ in months:
            stream.write(f"    {{{day}u, {year}, {month}, {days}u}},\n")
        stream.write("};\nconst size_t lunar_month_table_count = sizeof(lunar_month_table) / sizeof(lunar_month_table[0]);\n\n")
        stream.write("const lunar_term_record_t lunar_term_table[] = {\n")
        for day, index, _, _ in terms:
            stream.write(f"    {{{day}u, {index}u}},\n")
        stream.write("};\nconst size_t lunar_term_table_count = sizeof(lunar_term_table) / sizeof(lunar_term_table[0]);\n")


if __name__ == "__main__":
    months = make_months()
    terms = make_terms()
    emit(months, terms)
    print(f"generated {len(months)} lunar months and {len(terms)} solar terms")
